# Generated by Django 3.1 on 2020-09-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20200907_1321'),
        ('room', '0002_auto_20200906_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.host'),
        ),
    ]
