# Generated by Django 3.1 on 2020-09-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('user', '0003_merge_20200906_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'booking_status',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accomodation_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adult', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('infants', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.paymentmethod')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
