# Generated by Django 3.1 on 2020-09-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cleanliness_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('communication_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('check_in_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('accuracy_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('location_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('satisfaction_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
