# Generated by Django 3.1 on 2020-09-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200902_1832'),
        ('user', '0002_auto_20200902_2028'),
    ]

    operations = [
    ]
