# Generated by Django 3.1 on 2020-09-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200905_1725'),
        ('user', '0003_merge_20200906_2351'),
    ]

    operations = [
    ]
