# Generated by Django 3.1 on 2020-09-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20200903_2358'),
        ('user', '0004_auto_20200905_1725'),
    ]

    operations = [
    ]
