# Generated by Django 3.1 on 2020-09-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20200906_2351'),
        ('user', '0005_merge_20200907_1321'),
    ]

    operations = [
    ]
