# Generated by Django 3.1 on 2020-09-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20200909_1316'),
        ('user', '0005_merge_20200908_2155'),
    ]

    operations = [
    ]
