# Generated by Django 3.1 on 2020-09-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20200910_1536'),
        ('user', '0005_merge_20200910_1640'),
    ]

    operations = [
    ]
